title: "Documentation | Phish4All"
description: 
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

color_scheme: dark
mermaid:
  version: "9.1.3"
nav_enabled: true
logo: "assets/images/logo_title.svg"
favicon_icon: "assets/images/logo.ico"
